services:
    opstalent.form_factory.service:
        class: 'Opstalent\CrudBundle\Service\FormFactory'
        arguments:
            - '@form.factory'
    opstalent.form_config_resolver.service:
        class: 'Opstalent\CrudBundle\Service\FormConfigResolver'
        arguments:
            - '@annotations.reader'
