services:
    opstalent.form_factory.service:
        class: 'Opstalent\CrudBundle\FormFactory'
        arguments:
            - '@form.factory'
    opstalent.form_config_resolver.service:
        class: 'Opstalent\CrudBundle\FormConfigResolver'

    opstalent.form.event.listener:
        class: 'Opstalent\CrudBundle\FormEventListener'
        arguments:
          - '@doctrine.orm.entity_manager'
        tags:
          - { name: kernel.event_listener, event: form.post_bind }
    opstalent.form.request.listener:
        class: 'Opstalent\CrudBundle\Request\RequestListener'
        arguments:
          - '@opstalent.form_config_resolver.service'
          - '@opstalent.form_factory.service'
        tags:
          - { name: kernel.event_listener, event: kernel.request }
